package demo.invoices;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Client implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID")
	private Long id;
	@org.kie.api.definition.type.Label("Name")
	private String name;
	@org.kie.api.definition.type.Label("Address")
	private String address;

	private java.lang.String idType;

	public Client() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public java.lang.String getIdType() {
		return this.idType;
	}

	public void setIdType(java.lang.String idType) {
		this.idType = idType;
	}

	public Client(java.lang.Long id, java.lang.String name,
			java.lang.String address, java.lang.String idType) {
		this.id = id;
		this.name = name;
		this.address = address;
		this.idType = idType;
	}
}
